spring:
  application:
    name: BackGp
  datasource:
    url: jdbc:mysql://localhost:3306/gpmonde_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "gpmonde22@gmail.com"
    password: "chst eqjv vjgc dxst"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: "*"

jwt:
  secret: "ojJMx7uTkjO3Ov5BOjUimTFkk5Nb+zXvW+6wSRQUqSZeR9OjhseXki3vSA055PApH5ApNPXngdkkFfwOtax4eg=="

logging:
  level:
    org:
      springdoc: DEBUG
      springframework:
        web: DEBUG
      io:
        swagger.v3: DEBUG